Cleanup
greymatter-io/terraform-greymatter-ecs pull request #30
Opened 2020-09-28 20:15 UTC by zoemccormick

This PR cleans up a lot of smaller issues, including an attempt at improving clarity within the modules.

closes #11 
closes #20 
closes #24 
closes #28 

To test new env var setup - either check out the new docs [here](https://github.com/greymatter-io/terraform-greymatter-ecs/blob/cleanup/docs/install.md) or

Test with buttermilk sky:

check out `ecs_module_test` in bs, make sure you've awsumed bs-resources-admin, fill in values for `docker_gm_credentials`, `aws_access_key_id` and `aws_secret_access_key` and run `terraform apply`. The biggest change this PR makes it that you no longer need to do steps 1-3 of the [preinstall](https://github.com/greymatter-io/terraform-greymatter-ecs#pre-install).

This also adds coleman to the codeowners so in the future we won't need sofia to review everything :).

2020-09-28 22:00 UTC, dontlaugh requested changes
Some changes. I like the docs, but let's try to reduce the usage of internal language.

2020-09-28 22:00 UTC, dontlaugh commented on docs/code.md
> +The fabric module creates ECS services for control and control-api. Control is run with REST enabled, and a private route53 domain is created at `fabric.${var.dns_ns_name}` where other services withi
Is this internal language? Control should be "Grey Matter Control" or "The gm-control service".

2020-09-28 22:00 UTC, dontlaugh commented on docs/code.md
> +Control-api is bootstrapped with mesh configs found in [this file](../greymatter/modules/fabric/mesh/backup.json) - which creates a route from edge -> control-api at startup. Once the mesh comes up,
See above

2020-09-28 22:00 UTC, dontlaugh commented on docs/code.md
> +The edge module creates an ECS service for edge as well as a load balancer for ingress.
Add just a sentence about what edge is, and it's purpose.

2020-09-28 22:00 UTC, dontlaugh commented on docs/install.md
> +```bash
prefer `hcl` for syntax hint

2020-09-28 22:00 UTC, dontlaugh commented on docs/install.md
> +Note that when specifying ec2 instances and instance type, the ecs tasks will fail if allowed resources are not enough, see [the aws documentation](https://docs.aws.amazon.com/AmazonECS/latest/develo
```suggestion
Note that when specifying ec2 instances and instance type, the ecs tasks will fail if allowed resources are insufficient. See [the aws documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html#eni-trunking-supported-instance-types) on resources for instance types.
```

2020-09-28 22:00 UTC, dontlaugh commented on docs/install.md
> +SSL will be turned on on the Grey Matter services and sidecars on install, using the certificates specified in the [`gm/certs`](gm/certs) directory. The default certs checked in here are the quicksta
```suggestion
TLS will be turned on for the Grey Matter services and sidecars upon install. We use the certificates specified in the [`gm/certs`](gm/certs) directory. The default certs checked in here are self-signed certificates not suitable for production. To customize these, replace the content of the `ca.crt`, `cert.crt` and `key.crt` files for the services. Note that they must stay in the same directories and must still be named `ca.crt`, `cert.crt` and `key.crt`.
```

2020-09-28 22:00 UTC, dontlaugh commented on docs/install.md
> +If you are installing the `greymatter` module into an existing VPC, follow the instructions [below](#grey-matter-module) to set this up.
```suggestion
If you are installing the `greymatter` module into an existing VPC, follow the instructions [below](#grey-matter-module).
```

2020-09-28 22:00 UTC, dontlaugh commented on greymatter/modules/infrastructure/ecs-cluster.tpl
> +echo ECS_CLUSTER=${ecs_cluster} >> /etc/ecs/ecs.config
set a common variable for this path?

```
ECS_CONIFG=/etc/ecs/ecs.config
```

2020-09-28 22:00 UTC, dontlaugh commented on greymatter/modules/infrastructure/ecs-roles.tf
> +      "${data.aws_kms_alias.ssm.arn}"
nice

2020-09-29 14:49 UTC, dontlaugh approved these changes
lgtm

2020-09-29 14:51 UTC, sofiashalotenko approved these changes
lgtm

2020-09-29 15:32 UTC, merged